name: General check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, pgsql, xml, dom
        ini-values: post_max_size=256M, short_open_tag=On    
        tools: phpunit
    - name: Composer
      run: composer install
    - name: Test
      run: vendor/bin/phpunit
